name: models
description: "VueVideo Models"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  json_annotation: ^4.8.0
  equatable: ^2.0.0
  const_date_time: ^1.1.0
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  hive_generator: ^2.0.1
