name: user_repository
description: "VueVideo Mobile User Repository"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  json_annotation: ^4.8.0
  equatable: ^2.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  http: ^1.2.0
  const_date_time: ^1.1.0
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.9
  log:
    path: ../log
  models:
    path: ../models
  firebase_storage_mocks: ^0.6.1
  firebase_auth_mocks: ^0.13.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.6.0
  mockito: ^5.4.4
